USE [master]
GO

/****** Object:  Database [OMS]    Script Date: 8/30/2020 11:26:42 AM ******/
CREATE DATABASE [OMS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OMS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\OMS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OMS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\OMS_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OMS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OMS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OMS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OMS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OMS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OMS] SET ARITHABORT OFF 
GO

ALTER DATABASE [OMS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OMS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OMS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OMS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OMS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OMS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OMS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OMS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OMS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OMS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OMS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OMS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OMS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OMS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OMS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OMS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OMS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OMS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [OMS] SET  MULTI_USER 
GO

ALTER DATABASE [OMS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OMS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OMS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OMS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [OMS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OMS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [OMS] SET  READ_WRITE 
GO

